### ISSUE TITLE
make OMS optional 

### ISSUE THREAD

**Issue by flyisland** [SolaceProducts/pubsubplus-azure-quickstart-template#13]
For now, the "Log Analytics" is not supported by some regions, like East Asia, AUSTRALIA EAST etc. Which makes these regions not shown in the location dropdown list while applying this template.

![image](https://user-images.githubusercontent.com/547085/36241350-b48504d4-1250-11e8-9eb4-e548410bf093.png)

**Comment by KenBarr** [comment]
commit https://github.com/SolaceProducts/solace-azure-quickstart-template/commit/25dc8c4ce155960b9a0d21e575c180a145876cd1 allows OMS workspace to run in different region

**Comment by flyisland** [comment]
It works now with OMS workspace runs in a different region!
