### ISSUE TITLE
Singlenode Deployment Failed

### ISSUE THREAD

**Issue by sumeetkoshal** [SolaceProducts/pubsubplus-azure-quickstart-template#15]
![2018-03-02_00-15-00](https://user-images.githubusercontent.com/59294/36889483-00593cb8-1daf-11e8-990e-f47acddd1194.png)

**Comment by sumeetkoshal** [comment]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'configureVMRContainer'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\nading mirror speeds from cached hostfile\\nResolving Dependencies\\n--> Running transaction check\\n---> Package epel-release.noarch 0:7-9 will be installed\\n--> Finished Dependency Resolution\\n\\nDependencies Resolved\\n\\n================================================================================\\n Package Arch Version Repository Size\\n================================================================================\\nInstalling:\\n epel-release noarch 7-9 extras 14 k\\n\\nTransaction Summary\\n================================================================================\\nInstall 1 Package\\n\\nTotal download size: 14 k\\nInstalled size: 24 k\\nDownloading packages:\\nRunning transaction check\\nRunning transaction test\\nTransaction test succeeded\\nRunning transaction\\n Installing : epel-release-7-9.noarch 1/1 \\n Verifying : epel-release-7-9.noarch 1/1 \\n\\nInstalled:\\n epel-release.noarch 0:7-9 \\n\\nComplete!\\nLoaded plugins: fastestmirror, langpacks\\nLoading mirror speeds from cached hostfile\\n * epel: mirror.sjc02.svwh.net\\nResolving Dependencies\\n--> Running transaction check\\n---> Package jq.x86_64 0:1.5-1.el7 will be installed\\n--> Processing Dependency: libonig.so.2()(64bit) for package: jq-1.5-1.el7.x86_64\\n--> Running transaction check\\n---> Package oniguruma.x86_64 0:5.9.5-3.el7 will be installed\\n--> Finished Dependency Resolution\\n\\nDependencies Resolved\\n\\n================================================================================\\n Package Arch Version Repository Size\\n================================================================================\\nInstalling:\\n jq x86_64 1.5-1.el7 epel 153 k\\nInstalling for dependencies:\\n oniguruma x86_64 5.9.5-3.el7 epel 129 k\\n\\nTransaction Summary\\n================================================================================\\nInstall 1 Package (+1 Dependent package)\\n\\nTotal download size: 282 k\\nInstalled size: 906 k\\nDownloading packages:\\nPublic key for jq-1.5-1.el7.x86_64.rpm is not installed\\n--------------------------------------------------------------------------------\\nTotal 489 kB/s | 282 kB 00:00 \\nRetrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7\\nRunning transaction check\\nRunning transaction test\\nTransaction test succeeded\\nRunning transaction\\n Installing : oniguruma-5.9.5-3.el7.x86_64 1/2 \\nwarning: waiting for transaction lock on /var/lib/rpm/.rpm.lock\\n Installing : jq-1.5-1.el7.x86_64 2/2 \\n Verifying : oniguruma-5.9.5-3.el7.x86_64 1/2 \\n Verifying : jq-1.5-1.el7.x86_64 2/2 \\n\\nInstalled:\\n jq.x86_64 0:1.5-1.el7 \\n\\nDependency Installed:\\n oniguruma.x86_64 0:5.9.5-3.el7 \\n\\nComplete!\\nFile = ./deploy_vmr.sh\\nFile = ./semp_query.sh\\nFile = ./soltr-8.8.0.1017-vmr-enterprise-docker.tar.gz\\nFile = ./stderr\\nFile = ./stdout\\nFri Mar 2 08:12:01 UTC 2018 INFO: check to make sure we have a complete load\\nFri Mar 2 08:14:07 UTC 2018 INFO: Reference md5sum is: \\u001f�\\b\\b@��Z\\u0003soltr-8.8.0.1017-vmr-enterprise-docker.tar��\\nFri Mar 2 08:14:08 UTC 2018 INFO: Reference eval md5sum is: 472ad28fd25ff94e55d036543f904597\\nFri Mar 2 08:14:08 UTC 2018 INFO: Reference comm md5sum is: 40e50bf83ab9b6ddf8a3b64ef70ae7cd\\nFri Mar 2 08:14:08 UTC 2018 INFO: try 3 times to download from URL provided and validate it is Evaluation and Community edition VRM\\nFri Mar 2 08:14:08 UTC 2018 WARNING: CORRUPT SolOS load re-try 0\\nFri Mar 2 08:14:08 UTC 2018 WARNING: CORRUPT SolOS load re-try 1\\nFri Mar 2 08:14:08 UTC 2018 WARNING: CORRUPT SolOS load re-try 2\\nFri Mar 2 08:14:08 UTC 2018 ERROR: Failed to download SolOS exiting\\n\\n[stderr]\\nFri Mar 2 08:14:08 UTC 2018 ERROR: Failed to download SolOS exiting\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by sumeetkoshal** [comment]
I have uploaded enterprise docker VMR version to my box account and using that URL (it is accessible from anywhere).

**Comment by sumeetkoshal** [comment]
I had similar issue when deploying in GCP. For GCP I had to replace

wget -O /tmp/soltr-docker.tar.gz -nv -a ${LOG_FILE} ${REAL_HTML}

with

wget -O /tmp/soltr-docker.tar.gz -nv -a ${LOG_FILE} ${URL}

in file "vmr-install.sh" to make it work.

**Comment by solaceroland** [comment]
To use a custom/private VMR docker image, you need to upload the corresponding md5 file as well. The md5 file should have the same name as the VMR docker image, but with a suffix of ".md5".

For example, the following VMR docker image:

<base_url>/soltr-8.8.0.1017-vmr-enterprise-docker.tar.gz

should have the corresponding md5 file:

<base_url>/soltr-8.8.0.1017-vmr-enterprise-docker.tar.gz.md5

**Comment by bczoma** [comment]
This can be closed, verified it works. md5 file must be present if providing an image location.
