### ISSUE TITLE
Still using static IPs

### ISSUE THREAD

**Issue by KenBarr** [SolaceProducts/pubsubplus-azure-quickstart-template#16]
When moving to SolOS 8.7 features we should have moved to DNS names and not static IPs.  This will be the first step to be able to run in customers virtual networks.

**Comment by bczoma** [comment]
This issue is resolved by https://github.com/SolaceProducts/solace-azure-quickstart-template/pull/21 and c

**Comment by bczoma** [comment]
... and can be closed.

**Comment by PhilippeKhalife** [comment]
Closing fixed in #21
