### ISSUE TITLE
Allow router-names as parameters

### ISSUE THREAD

**Issue by wlyeow** [SolaceProducts/pubsubplus-azure-quickstart-template#19]
Writing this for Vidya (RT28233).

HA triplet router-names are hard set as `primary`, `backup` and `monitor` in [deploy_vmr.sh](../blob/2bfe57574a833dbb8355a23629ded207c81f02a0/scripts/deploy_vmr.sh). This poses a problem if a user needs to quick-start a DR-mate site, and will end up having the same names as the mate site. Changing the router names of the HA triplet would be mean reconfiguring the entire redundancy all over again.

**Comment by bczoma** [comment]
The router names now prepended with the DNS Label for IP parameter. E.g. for the primary it is routername=${dns_prefix}primary

With this router-names will be unique for each deployment.

**Comment by bczoma** [comment]
This can be closed now.
