### ISSUE TITLE
Singlenode Deployment Not Working

### ISSUE THREAD

**Issue by rabreu1900** [SolaceProducts/pubsubplus-azure-quickstart-template#20]
Getting the following error when using the template:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'configureVMRContainer'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=127\\n[stdout]\\n\\n[stderr]\\n/bin/sh: WOaW6IsA3: command not found\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by rabreu1900** [comment]
Although the deployment ended with an error, the VMR seems to be working fine.

**Comment by bczoma** [comment]
Tested with latest and single node deployment worked for me with no issues. This can be closed.
