### ISSUE TITLE
Step-2 Deploy to Azure throws error

### ISSUE THREAD

**Issue by sumeetkoshal** [SolaceProducts/pubsubplus-azure-quickstart-template#24]
Hmmm...
Sorry, the portal took a long time to load. Click 'Try again' to reload.
Looks like something went wrong

**Comment by bczoma** [comment]
Hi Sumeet, can you provide any more details of the issue, like the error message?

**Comment by sumeetkoshal** [comment]
When i click "Deploy to Azure" link from this github project README, It takes me to Azure portal and I see the screen attached.
![image](https://user-images.githubusercontent.com/59294/44805693-c3d97100-ab79-11e8-97e0-f7203c0ddde7.png)

**Comment by bczoma** [comment]
Thank you. I cannot seem to be able to reproduce it at my end. Is it reproducible for you?

**Comment by sumeetkoshal** [comment]
Yes every time I click that link I see the same issue.

Regards
[photo]

Sumeet Koshal
Principal Architect
Cell: +1-669-248-9711<tel:+1-669-248-9711>
Email: Sumeet.Koshal@Solace.com<mailto:Sumeet.Koshal@Solace.com>
Solace.com<https://solace.com/> | My LinkedIn<https://www.linkedin.com/in/sumeetkoshal/>



Useful Links:
http://dev.solace.com<http://dev.solace.com/>
http://dev.solace.com/blog/
http://dev.solace.com/demos/
http://dev.solace.com/docs/integration-guides/

On Aug 29, 2018, at 10:58 AM, Balázs Czoma <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you. I cannot seem to be able to reproduce it at my end. Is it reproducible for you?

**Comment by bczoma** [comment]
Sumeet, can this apply? https://dajbych.net/azure-portal-hmmm-looks-like-something-went-wrong

Does this behavior occur in a different browser as well?

**Comment by PhilippeKhalife** [comment]
No response, closing - please open a new issue if the problem is observed again.
