### ISSUE TITLE
Storage using xfs / overlay

### ISSUE THREAD

**Issue by solacedbaik** [SolaceProducts/pubsubplus-azure-quickstart-template#8]
I noticed the following about the docker hosts created by the template:
Storage Driver: overlay
 Backing Filesystem: xfs

In comparison, the AWS docker host uses:
Storage Driver: overlay2
 Backing Filesystem: extfs

Any thoughts on making them the same?

**Comment by KenBarr** [comment]
Azure and AWS solutions run different base OS and can run different Docker releases. They will not move together lock step. There is no plan to standardize at this layer.
